build_image: shippableimages/ubuntu1404_nodejs

language: node_js

node_js:
  - "0.10.32"

before_install:
  - sudo apt-get update


install:
  - sudo apt-get install -y llvm-3.4 clang-3.4 libunwind8-dev libuv-dev make
  - sudo npm install -g coffee-script
  - sudo npm install -g node-gyp
  - sudo npm install -g mocha

before_script:
  - make

script:
  - env
  - make bootstrap
  - make check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
