language: objective-c

before_install:
  - brew update
  - brew tap homebrew/versions

install:
  - export PATH=$PATH:/usr/local/share/npm/bin
  - sh ./ci/install-node.sh
  - sh ./ci/install-coffeescript.sh
  - sh ./ci/install-llvm.sh

before_script:
  - export LLVM_SUFFIX=
  - export PATH=$PATH:/usr/local/share/npm/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - llvm-config --cflags
  - ls /usr/local/opt/llvm/bin
  - ls /usr/local/opt/llvm/share/llvm
  - make

script:
  - env
  - export LLVM_SUFFIX=
  - export PATH=$PATH:/usr/local/share/npm/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - export NODE_PATH=`make -C test node-path`
  - touch test/expected/*.expected-out
  - EJS_STAGE=0 EJS_DRIVER="`pwd`/ejs -q --srcdir" make -C test check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
  - EJS_STAGE=1 EJS_DRIVER="`pwd`/ejs.exe -q --srcdir" make -C test check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
