buildimage: shippableimages/ubuntu1404_nodejs

language: c++

before_install:
  - sudo apt-get update


install:
  - sudo apt-get install llvm-3.4 clang-3.4 nodejs-legacy libunwind8-dev libuv-dev
  - sudo npm install -g coffee-script
  - sudo npm install -g node-gyp
  - sudo npm install -g mocha

before_script:
  - make

script:
  - env
  - make bootstrap
  - make check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
